import styles from './sass/style.scss';
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
import './js/integradores/lazy-map.js';
import './js/integradores-form.js';
import './js/integradores/mapa.js';
import 'popper.js';
import 'bootstrap';
import 'slick-carousel';
import '@fortawesome/fontawesome-pro/js/all';
import 'scrollreveal';
import './js/custom';
import './js/_form_calculo';